pool:
  vmImage: 'vs2017-win2016'

trigger:
  branches:
    include:
      - master  

steps:
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)\terraform-code'
    inputs:
      SourceFolder: terraform-code
      Contents: '*.*'
      TargetFolder: $(Build.ArtifactStagingDirectory)\terraform-code
      CleanTargetFolder: true
      OverWrite: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: drop
  